const dummyData = {
  patients: [
    {
      id: "P1001",
      name: "John Doe",
      age: 42,
      gender: "Male",
      email: "john@example.com",
    },
    {
      id: "P1002",
      name: "Jane Smith",
      age: 35,
      gender: "Female",
      email: "jane@example.com",
    },
    {
      id: "P1003",
      name: "Michael Johnson",
      age: 50,
      gender: "Male",
      email: "michael@example.com",
    },
    {
      id: "P1004",
      name: "Emily Davis",
      age: 29,
      gender: "Female",
      email: "emily@example.com",
    },
    {
      id: "P1005",
      name: "Chris Brown",
      age: 40,
      gender: "Other",
      email: "chris@example.com",
    },
  ],

  feedbacks: [
    {
      id: "F3001",
      name: "Thomas Wright",
      rating: 5,
      comment: "Excellent service!",
      date: "2025-03-02",
      email: "thomas@example.com",
    },
    {
      id: "F3002",
      name: "Sophia Miller",
      rating: 4,
      comment: "Very professional.",
      date: "2025-03-01",
      email: "sophia@example.com",
    },
    {
      id: "F3003",
      name: "Daniel Wilson",
      rating: 3,
      comment: "Good, but can improve.",
      date: "2025-02-28",
      email: "daniel@example.com",
    },
    {
      id: "F3004",
      name: "Emma Johnson",
      rating: 5,
      comment: "Highly recommended!",
      date: "2025-02-27",
      email: "emma@example.com",
    },
    {
      id: "F3005",
      name: "Liam White",
      rating: 2,
      comment: "Needs better support.",
      date: "2025-02-26",
      email: "liam@example.com",
    },
  ],

  contacts: [
    {
      id: "C2001",
      name: "David Miller",
      email: "david@example.com",
      subject: "Appointment Request",
      date: "2025-03-02",
      message: "I'd like to schedule an appointment.",
      phone: "555-123-4567",
    },
    {
      id: "C2002",
      name: "Olivia Brown",
      email: "olivia@example.com",
      subject: "Billing Inquiry",
      date: "2025-03-01",
      message: "I have a question about my bill.",
      phone: "555-987-6543",
    },
    {
      id: "C2003",
      name: "Ethan Green",
      email: "ethan@example.com",
      subject: "Medical Records",
      date: "2025-02-28",
      message: "How can I access my records?",
      phone: "555-456-7890",
    },
    {
      id: "C2004",
      name: "Ava Thompson",
      email: "ava@example.com",
      subject: "Prescription Refill",
      date: "2025-02-27",
      message: "Need a refill for my medication.",
      phone: "555-321-6789",
    },
    {
      id: "C2005",
      name: "Noah Anderson",
      email: "noah@example.com",
      subject: "General Inquiry",
      date: "2025-02-26",
      message: "Just had a few questions.",
      phone: "555-654-3210",
    },
  ],
};

export default dummyData;
